.github/workflows/links.yml
DEVELOPER_GUIDE.md
logstash-output-opensearch.gemspec
scripts/Dockerfile
scripts/opendistro/docker-compose.override.yml
scripts/opensearch/docker-compose.override.yml

Update gem spec and DEVELOPER_GUIDE.
#6 

Add developer guide

---

Gemfile
spec/integration/outputs/create_spec.rb
spec/integration/outputs/ingest_pipeline_spec.rb
spec/integration/outputs/metrics_spec.rb
spec/integration/outputs/no_opensearch_on_startup_spec.rb
spec/integration/outputs/painless_update_spec.rb
spec/integration/outputs/retry_spec.rb
spec/integration/outputs/templates_spec.rb
spec/integration/outputs/update_spec.rb
spec/opensearch_spec_helper.rb

There is an OS command injection vulnerability in Ruby Rake before 12.3.3 in Rake::FileList when supplying a filename that begins with the pipe character |. Though suggested remedy is to update to 12.3.3, we can remove this pinning since it was required only for Logstash 5.x.
#10 

FIX CVE-2020-8130

---

.github/workflows/ci.yml
scripts/Dockerfile
scripts/logstash-run.sh
scripts/opendistro/docker-compose.override.yml
scripts/opensearch/docker-compose.override.yml
scripts/opensearch/docker-run.sh
scripts/opensearch/docker-setup.sh
scripts/unit-test/docker-compose.yml
scripts/unit-test/docker-run.sh
scripts/unit-test/docker-setup.sh
scripts/unit-test/logstash-run.sh

Separate unit test and integration test

Refactor unit tests and integration tests

---

.github/workflows/CD.yml
.github/workflows/CI.yml

Download logstash, build plugin, install plugin and
publish logstash-oss-7.13.2-linux-x86_64.tar.gz
- [] New functionality has been documented.

Add workflow to publish linux x86_64

---

.github/draft-release-notes-config.yml
.github/workflows/draft-release-notes-workflow.yml
.gitignore
dockerfiles/Dockerfile
dockerfiles/build.sh
dockerfiles/docker-compose.yml
dockerfiles/logstash-opensearch-sample.conf
dockerfiles/run.sh
lib/logstash/outputs/opensearch/http_client/pool.rb
logstash-output-opensearch.gemspec

Added script to build docker image.

Create docker files for build

---

lib/logstash/outputs/opensearch/http_client_builder.rb
lib/logstash/plugin_mixins/opensearch/api_configs.rb
spec/unit/outputs/opensearch_ssl_spec.rb

Since OpenSearch supports TLS certificate authentication,
this plugin should support those mechanism as well.
#30 

Support TLS Certificate

---

.github/draft-release-notes-config.yml
.github/workflows/draft-release-notes-workflow.yml
.gitignore
DEVELOPER_GUIDE.md
README.md
dockerfiles/Dockerfile
dockerfiles/build.sh
dockerfiles/docker-compose.yml
dockerfiles/logstash-opensearch-sample.conf
dockerfiles/run.sh
lib/logstash/outputs/opensearch.rb
lib/logstash/outputs/opensearch/distribution_checker.rb
lib/logstash/outputs/opensearch/http_client.rb
lib/logstash/outputs/opensearch/http_client/pool.rb
lib/logstash/outputs/opensearch/http_client_builder.rb
lib/logstash/plugin_mixins/opensearch/api_configs.rb
lib/logstash/plugin_mixins/opensearch/common.rb
lib/logstash/plugin_mixins/opensearch/noop_distribution_checker.rb
logstash-output-opensearch.gemspec
spec/unit/outputs/opensearch/http_client/pool_spec.rb
spec/unit/outputs/opensearch_ssl_spec.rb

Backport to 1.x from main

---

lib/logstash/outputs/opensearch/distribution_checker.rb
spec/unit/outputs/opensearch/http_client/pool_spec.rb

Signed-ofr-by: Vijayan Balasubramanian <balasvij@amazon.com>
Added version and major version to error message if cluster
is not compatible.
#35

Update error message

---

.github/workflows/CI.yml
DEVELOPER_GUIDE.md
scripts/Dockerfile
scripts/opendistro/Dockerfile.opendistro
scripts/opendistro/docker-compose.override.yml
scripts/opendistro/docker-compose.yml
scripts/opendistro/elasticsearch-run.sh
scripts/opensearch/Dockerfile.opensearch
scripts/opensearch/docker-compose.override.yml
scripts/opensearch/docker-compose.yml
scripts/opensearch/opensearch-run.sh
scripts/unit-test/docker-compose.yml

Clean up docker files to remove run file.
Allow CI to run against multiple logstash-oss version
and multiple openserach version.
#58 

Update workflow to configure logstash version

---

.github/workflows/CI.yml
logstash-output-opensearch.gemspec

Backport https://github.com/opensearch-project/logstash-output-opensearch/pull/70 to 1.1 branch

Backport to 1.1

---

lib/logstash/outputs/opensearch.rb
lib/logstash/outputs/opensearch/http_client.rb

comments in code refer to `docs-beta` causing an unneeded forward in one case and and a 404 in the other. 
n/a

Comment docs

---

lib/logstash/outputs/opensearch/http_client/manticore_adapter.rb

Adding optional parameters required for aws_iam authentication inside auth_type
https://github.com/opensearch-project/logstash-output-opensearch/issues/83

Adding optional parameters required for authentication inside auth_type

---

lib/logstash/outputs/opensearch/http_client/manticore_adapter.rb
spec/integration/outputs/index_spec.rb
spec/unit/outputs/opensearch/http_client/manticore_adapter_spec.rb

Adding basic_auth as a new authentication mechanism by also supporting existing Master credentials (user and password without auth_type). Also added, unit tests and integration tests to validate.
https://github.com/opensearch-project/logstash-output-opensearch/issues/74
I tested this updated code with opensearch output configurations by taking the standard input and verified the message in the index:

Adding basic_auth authentication

---

lib/logstash/outputs/opensearch/http_client.rb
lib/logstash/outputs/opensearch/http_client_builder.rb
lib/logstash/plugin_mixins/opensearch/api_configs.rb
spec/integration/outputs/index_spec.rb
spec/unit/outputs/opensearch/http_client_spec.rb
spec/unit/outputs/opensearch_spec.rb

This fix prevents http status 413
Fixes old bug carrying over from logstash-output-elasticsearch: logstash-plugins/logstash-output-elasticsearch#785

Make default target_bulk_bytes below AWS limit, but make it configurable

---

CONTRIBUTING.md
release/docker/build-docker-multi-arch.sh

Update Copyright license header in CONTRIBUTING.md and other file
https://github.com/opensearch-project/logstash-output-opensearch/issues/51

Update copyright license header

---

.github/workflows/CI.yml
.github/workflows/links.yml
logstash-output-opensearch.gemspec
spec/integration/outputs/compressed_indexing_spec.rb
spec/integration/outputs/create_spec.rb
spec/integration/outputs/delete_spec.rb
spec/integration/outputs/index_spec.rb
spec/integration/outputs/index_version_spec.rb
spec/integration/outputs/ingest_pipeline_spec.rb
spec/integration/outputs/metrics_spec.rb
spec/integration/outputs/no_opensearch_on_startup_spec.rb
spec/integration/outputs/painless_update_spec.rb
spec/integration/outputs/retry_spec.rb
spec/integration/outputs/sniffer_spec.rb
spec/integration/outputs/templates_spec.rb
spec/integration/outputs/update_spec.rb
spec/opensearch_spec_helper.rb

* Use OpenSearch::Client instead of Elasticsearch.
* Update CI to test last two minor release.
#55 

Add dependency to opensearch-ruby

---

.gitignore
logstash-output-opensearch.gemspec

Adding signing key path to gemspec
https://github.com/opensearch-project/logstash-output-opensearch/issues/100

Adding Signing key path to gemspec

---

.github/workflows/backport.yml
DEVELOPER_GUIDE.md

Add auto backport workflow to backport PRs for release. 
https://github.com/opensearch-project/logstash-output-opensearch/issues/115

Add Backport workflow

---

.github/workflows/links.yml

Add a fix to the failing link checker

Fix link checker

---

.github/workflows/backport.yml

Using Github App token in the auto-backport workflow to trigger CI on auto-backport PRs since events created by secrets.GITHUB_TOKEN cannot trigger other workflows. 
https://github.com/opensearch-project/logstash-output-opensearch/issues/115

Use GitHub App token to trigger CI for backport PRs

---

.github/workflows/CI.yml

Bumping up logstash version to 7.17.1

Bump logstash version to 7.17.1

---

logstash-output-opensearch.gemspec

opensearch-ruby 2.0 has breaking changes. Hence, update opensearch-ruby to use only from 1.x release.

Update opensearch-ruby dependency to pin major version as 1.0

---

lib/logstash/outputs/opensearch/http_client.rb
spec/unit/outputs/opensearch/http_client_spec.rb

Use absolute path for template endpoint ('/_template' instead of '_template')
Fixes #124 
Fixes #144
Resolves this error installing template:
`[2022-06-08T10:02:44,587][ERROR][logstash.outputs.opensearch][devicelogs_http_input] Failed to install template {:message=>"bad component(expected absolute path component): _template/<template name>", :exception=>URI::InvalidComponentError,  ...`

Use absolute path for template endpoint

---

lib/logstash/outputs/opensearch/templates/ecs-disabled/2x.json

Closes: #145
Signed-off-by: Cole White <cwhite@wikimedia.org>
Adds a 2x.json template copied from 1x.json to prevent `Failed to load default template for OpenSearch v2 with ECS disabled` error.
#145 

Add 2x default template.

---

.github/workflows/CI.yml
scripts/Dockerfile
scripts/logstash-run.sh
spec/integration/outputs/compressed_indexing_spec.rb
spec/integration/outputs/index_spec.rb
spec/integration/outputs/parent_spec.rb
spec/opensearch_spec_helper.rb

Fix the integration tests to work with OpenSearch 2.x and add OpenSearch 2.1.0 in the CI test matrix.
Also update the OpenSearch 1.x version in CI from 1.2.1 to 1.3.4
https://github.com/opensearch-project/logstash-output-opensearch/issues/148

Make ci compatible with os2.x

---

logstash-output-opensearch.gemspec
release-notes/logstash-output-opensearch.release-notes-1.3.0.md

Signed-off-by: Deep Datta <deedatta@amazon.com>
[Describe what this change achieves]

Update version to 1.3.0 and add a release note for this version. (#156)

---

COMPATIBILITY.md
README.md
lib/logstash/outputs/opensearch/http_client/manticore_adapter.rb
logstash-output-opensearch.gemspec

Support assume IAM role from Service Account
#96 
@dlvenable

Upgrade to aws sdk v3

---

Rakefile
lib/logstash/outputs/opensearch.rb
lib/logstash/outputs/opensearch/http_client.rb
lib/logstash/outputs/opensearch/http_client_builder.rb
lib/logstash/outputs/opensearch/template_manager.rb
lib/logstash/outputs/opensearch/templates/ecs-disabled/1x_index.json
lib/logstash/outputs/opensearch/templates/ecs-disabled/2x_index.json
lib/logstash/outputs/opensearch/templates/ecs-disabled/7x_index.json
lib/logstash/outputs/opensearch/templates/ecs-v8/1x_index.json
lib/logstash/outputs/opensearch/templates/ecs-v8/2x_index.json
lib/logstash/outputs/opensearch/templates/ecs-v8/7x_index.json
spec/unit/outputs/opensearch/http_client_spec.rb
spec/unit/outputs/opensearch/template_manager_spec.rb

Add a config option legacy_template, type:bool, default:true
When false, it will use the `_template API`, when true it will use the `_index_template` API.
Note: There was no clean way to check versions while enabling _index_template. If the config is explicitly set to `false` for OpenDistro version <= 1.8.0 (ES version < 7.8) it will throw errors while installing templates.
[#12](https://github.com/opensearch-project/logstash-output-opensearch/issues/12)

Support index templates

---

lib/logstash/outputs/opensearch.rb
lib/logstash/outputs/opensearch/http_client.rb
lib/logstash/outputs/opensearch/http_client/pool.rb
lib/logstash/outputs/opensearch/http_client_builder.rb

Signed-off-by: Deep Datta <deedatta@amazon.com>
Add a skip_healthcheck config, which is false by default. When set to true it will not send a GET request to the healthcheck endpoint. However it will still send the HEAD request to make sure the node is alive.
To get a version number in that scenario, add another config default_server_major_version which is 2 by default denoting OpenSearch 2.x, but can be changed by the user.
[Add a config to skip doing a GET on the healthcheck endpoint #165](https://github.com/opensearch-project/logstash-output-opensearch/issues/165)
For more information on following Developer Certificate of Origin and signing off your commits, please check …

Adding a config to skip_healthcheck

---

lib/logstash/outputs/opensearch/http_client.rb

Signed-off-by: Hai Yan <oeyh@amazon.com>
This PR adds a change to close gzip writer before sending the data stream so that it can be decompressed properly. 
Tested against an AOS domain and was able to send logs over successfully when using partial bulk requests.
Fixes #182 

Fix a gzip compression issue when sending partial bulk requests

---

.github/workflows/release-drafter.yml
RELEASING.md
jenkins/release.jenkinsFile

This change add release workflows for logstash-output-opensearch plugin that is released on rubygems.
See https://github.com/opensearch-project/opensearch-build/issues/1234 for more details about end to end process.
The secrets role has been added to this repo as well as new api key required has been generated. I'll be adding the webhook once this PR is merged.
Thanks!
closes https://github.com/opensearch-project/opensearch-build/issues/3139

Add release workflows

---

logstash-output-opensearch.gemspec
release-notes/logstash-output-opensearch-release-notes-2.0.1.md

Signed-off-by: Shivani Shukla <sshkamz@amazon.com>
* Updates version to 2.0.1
* Adds release notes for 2.0.1
Contributes as pre-release step of 2.0.1 [#3139](https://github.com/opensearch-project/opensearch-build/issues/3139)

Updates version to 2.0.1 and adds release notes

---

.github/CODEOWNERS

Fixes the `CODEOWNERS` file by putting all users on a single line.
See: https://github.com/opensearch-project/logstash-output-opensearch/pull/203#discussion_r1142562128

Fixes CODEOWNERS by putting all on a single line.

---

jenkins/release.jenkinsFile

Update build lib to 5.7.1 to consume sigunature verification changes
#218

Update build lib to 5.7.1 to consume sigunature verification changes

---

lib/logstash/plugin_mixins/opensearch/common.rb
release-notes/logstash-output-opensearch-release-notes-2.0.1.md
release-notes/logstash-output-opensearch-release-notes-2.0.2.md
release-notes/logstash-output-opensearch-release-notes-next.md
spec/unit/outputs/opensearch_spec.rb

AOSS does not support GET, don't attempt to retrieve cluster UUID
Closes https://github.com/opensearch-project/logstash-output-opensearch/issues/186

Fix: remove warning message on cluster UUID retrieval failure with AOSS.

---

DEVELOPER_GUIDE.md
docs/building_custom_docker_images.md

This MR add a documentation to build Logstash custom image with opensearch plugin/
Follow-up to this question #209 

Add documentation for building Logstash custom image with opensearch plugin

---

.github/CODEOWNERS
MAINTAINERS.md

Adding @dblock as a maintainer as voted upon by the current maintainers.
He has made a [number of contributions](https://github.com/opensearch-project/logstash-output-opensearch/pulls?q=is%3Apr+is%3Aclosed+author%3Adblock) including fixing a bug (#217) that affected sigV4 signing.
Additionally, he has been active in the issues, PR reviews, and recent releases.
N/A

Adds dblock as a maintainer

---

.github/workflows/CI.yml
DEVELOPER_GUIDE.md
README.md
release/docker/logstash-opensearch-sample.conf
scripts/docker.env
scripts/logstash-run.sh
scripts/opendistro/docker-compose.override.yml
scripts/opensearch/docker-compose.override.yml
spec/integration/outputs/index_spec.rb
spec/opensearch_spec_helper.rb

There were recent changes to security demo configuration setup which now requires a custom admin Password to be setup. This PR updates the documentation and related code change.

Addresses changes made to security demo config install tool

---

.github/workflows/CI.yml
lib/logstash/outputs/opensearch/http_client/manticore_adapter.rb
scripts/opendistro/docker-run.sh
scripts/opendistro/docker-setup.sh
scripts/opensearch/docker-run.sh
scripts/opensearch/docker-setup.sh
scripts/run.sh
scripts/unit-test/docker-run.sh
scripts/unit-test/docker-setup.sh

Adds the `account_id` configuration to the `AWSIAMCredential` struct to work with the latest versions of the AWS SDK for Ruby. Leaving this as `nil` should be sufficient because we do not use account-based endpoints.
Test against the latest versions of Logstash during the integration testing to also test against these versions of the AWS SDK. For Logstash 7, this is 7.17.24. For Logstash 8, this is 8.15.3.
The GitHub Actions runners now have `docker compose` instead of `docker-compose`, so I also updated all those references.
Resolves #258
For more information on following Developer Certificate of Origin and signing off your commits, please check …

Support the latest versions of Logstash and the AWS SDK for Ruby.

---

RELEASING.md

This updates the `RELEASING.md` file to help with future releases.
The previous releases have all been from `main` so this documents that. Additionally, it adds instructions for tagging locally. And it fixes a URL to the build system.
N/A

Updates the RELEASING.md documentation for the process

---

README.md
logstash-output-opensearch.gemspec
release-notes/logstash-output-opensearch-release-notes-next.md

Builds opensearch plugin that can be deployed against the more recent versions of logstash.
Solves this:
```
root@625ca0aeeae7:/usr/share/logstash# DEBUG=1 bin/logstash-plugin install file:///usr/share/logstash/logstash-integration-aws-0.1.0.pre.gem.zip
Using bundled JDK: /usr/share/logstash/jdk
Processing jvm.options file at `/usr/share/logstash/config/jvm.options`
Appending jvm options from environment LS_JAVA_OPTS …
```

Build against aws-sdk-core.
