DEVELOPER_GUIDE.md, README.md, lib/logstash/outputs/opensearch.rb, lib/logstash/outputs/opensearch/distribution_checker.rb, lib/logstash/outputs/opensearch/http_client.rb, lib/logstash/outputs/opensearch/http_client/pool.rb, lib/logstash/outputs/opensearch/http_client_builder.rb, lib/logstash/plugin_mixins/opensearch/common.rb, lib/logstash/plugin_mixins/opensearch/noop_distribution_checker.rb, spec/unit/outputs/opensearch/http_client/pool_spec.rb
Checks whether connecting cluster is supported or not.
Set connection status to dead if cluster is neither opensearch
not oss with major version != 7.
#8
=> Add distribution check

.github/draft-release-notes-config.yml, .github/workflows/draft-release-notes-workflow.yml, .gitignore, DEVELOPER_GUIDE.md, README.md, dockerfiles/Dockerfile, dockerfiles/build.sh, dockerfiles/docker-compose.yml, dockerfiles/logstash-opensearch-sample.conf, dockerfiles/run.sh, lib/logstash/outputs/opensearch.rb, lib/logstash/outputs/opensearch/distribution_checker.rb, lib/logstash/outputs/opensearch/http_client.rb, lib/logstash/outputs/opensearch/http_client/pool.rb, lib/logstash/outputs/opensearch/http_client_builder.rb, lib/logstash/plugin_mixins/opensearch/api_configs.rb, lib/logstash/plugin_mixins/opensearch/common.rb, lib/logstash/plugin_mixins/opensearch/noop_distribution_checker.rb, logstash-output-opensearch.gemspec, spec/unit/outputs/opensearch/http_client/pool_spec.rb, spec/unit/outputs/opensearch_ssl_spec.rb
=> Backport to 1.0 from main

README.md
=> Update README with badge url

README.md
Update copyright to OpenSearch.
#51 
=> Fix copyright in README

CONTRIBUTING.md, DEVELOPER_GUIDE.md, README.md
- Update unreachable url to valid.
- Update example.
=> Fix unreachable url

.github/workflows/CI.yml, logstash-output-opensearch.gemspec
Update version to 1.1.0
Add support to test against 7.13.4
=> Update minor version

spec/unit/outputs/opensearch/http_client/manticore_adapter_spec.rb
Adding unit tests for aws_iam Authentication
https://github.com/opensearch-project/logstash-output-opensearch/issues/59
=> Adding unit tests for aws_iam Authentication

README.md
Fixed Documentation link in README file which is pointing to project website
https://github.com/opensearch-project/logstash-output-opensearch/issues/61
=> Fixed Documentation bug in README

.github/workflows/CI.yml, scripts/opensearch/Dockerfile.opensearch
Use opensearch 1.2.0 version for integration test.
=> Run integration test against latest version

logstash-output-opensearch.gemspec
Update version on main to 1.2.0
https://github.com/opensearch-project/logstash-output-opensearch/issues/98
=> Update Version on main to 1.2.0

release-notes/logstash-output-opensearch.release-notes-1.2.0.md
Add Release Notes for 1.2.0
https://github.com/opensearch-project/logstash-output-opensearch/issues/102
=> Adding release-notes 1.2

release-notes/logstash-output-opensearch.release-notes-1.2.0.md
=> Update release-notes 1.2

.github/workflows/CI.yml
Update logstash to 7.16.1
Update opendistro to 1.13.3
Update OpenSearch to 1.2.1
#98 #55 
=> Update upstream version to latest release

.github/workflows/CI.yml
Update logstash, search cluster to latest version
#55 
=> Backport #109 to 1.2

.gitignore, build.sh
Introduced build script to build gemspec file.
This will be used by jenkins job to build and upload to rubygems.org.
#98
=> Add build script

.gitignore, build.sh, release/tar/generate-artifact.sh
=> Backport #111 and #112

README.md
Add sample output configuration to README
https://github.com/opensearch-project/logstash-output-opensearch/issues/79
=> Update README with sample configuration

.github/workflows/CI.yml
use latest logstash oss version 7.16.3
#121 
=> Update upstream version

.github/workflows/delete_backport_branch.yml
Workflow to automatically delete the branches created by the [backport action ](https://github.com/opensearch-project/logstash-output-opensearch/blob/main/.github/workflows/backport.yml)of type backport/*.
https://github.com/opensearch-project/logstash-output-opensearch/issues/115
=> add auto delete backport branch workflow

Gemfile, logstash-output-opensearch.gemspec
Signed-off-by: Vacha Shah <vachshah@amazon.com>
Upgrading json gem to version >= 2.3.0.
=> Upgrading json gem

MAINTAINERS.md
Updating Maintainers list
Adding Deep, David and Shivani to the Maintainers list
=> Add Deep, David and Shivani to the Maintainers list

logstash-output-opensearch.gemspec, release-notes/logstash-output-opensearch.release-notes-1.3.0.md
Update version to 1.3.0 and add a release note for this version
=> Update version to 1.3.0 and add a release note for this version.

release-notes/logstash-output-opensearch.release-notes-2.0.0.md
Signed-off-by: Deep Datta <deedatta@amazon.com>
Add release note for 2.0.0
=> Add release note for 2.0.0

README.md
Signed-off-by: Deep Datta <deedatta@amazon.com>
Update the OpenSearch documentation website link for this plugin
=> Update the OpenSearch documentation website link for this plugin

.gitignore, jenkins/release.jenkinsFile
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
The old lib version had a bug that does not download the release artifact properly. Hence, upgrading to new version
=> Upgrade jenkins library version

jenkins/release.jenkinsFile
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
There was a miss in the previous PR. I forgot to upgrade the jenkins lib version. My bad! :( 
=> Upgrade jenkins lib version

.github/CODEOWNERS, MAINTAINERS.md
Baselines the MAINTAINERS.md and CODEOWNERS files.
@VijayanB , @VachaShah 
@asifsmohammed , @oeyh 
Resolves #196
=> Baselines the MAINTAINERS.md and CODEOWNERS files.

release-notes/logstash-output-opensearch-release-notes-2.0.2.md
Adds release notes for v2.0.2
N/A
=> Adds release notes for v2.0.2

logstash-output-opensearch.gemspec
Update the Gem spec version to `2.0.2`.
N/A
=> Update the plugin version to 2.0.2.

.github/workflows/CI.yml
Upgrade upstream logstash-oss to 8.12.1
Fixes #235
=> Upgrade logstash-oss to 8.12.1

README.md
Missing /usr/share/logstash/ in the last command
- [ x] Commits are signed as per the DCO using --signoff 
=> Update README.md fix path typo

.github/CODEOWNERS, MAINTAINERS.md
Now that I don't work on OpenSearch full time I won't have the bandwidth to maintain this one, sorry. Please remove me from maintainers.
=> Stepping dblock@ down to Emeritus.

README.md
This change adds a link to code so that users can see all of the configurable plugin options
#274 
- [NA] New functionality includes testing.
- [NA] All tests pass
- [NA] New functionality has been documented.
- [NA] New functionality has documentation added
=> Link to all config parameters from README
